1-gantt-axes-groups
blacklabel/highcharts-fundamentals-hubertkozik pull request #2
Opened 2022-05-04 11:21 UTC by hubertkozik

2022-05-13 14:49 UTC, raf18seb requested changes

2022-05-13 14:49 UTC, raf18seb commented on highcharts-api/highcharts-gantt/1-gantt-axes-groups/main.js
> +                list: ['%A, %e %b, %Y']
This solution is good, but only when labels are grouped into weeks.
What if I wanted to keep the format of the labels this way with changed the "First" points' `start` to `1530002400000`?

2022-08-18 17:08 UTC, magdalena-gut requested changes

2022-08-18 17:08 UTC, magdalena-gut commented on highcharts-api/highcharts-gantt/1-gantt-axes-groups/main.js
> +    {
I would say, this part of the code is unnecessary:

```
  {
        opposite: false,
        visible: false,
    }
```

2022-08-18 17:08 UTC, magdalena-gut commented on highcharts-api/highcharts-gantt/1-gantt-axes-groups/main.js
> +        uniqueNames: true,
commas ;)

2023-12-12 08:49 UTC, closed without merging