exercise/highcharts-8-part3
blacklabel/highcharts-fundamentals-hubertkozik pull request #6
Opened 2022-05-05 12:00 UTC by hubertkozik

2022-05-27 14:10 UTC, Izothep requested changes
Cool, working, small comments included :)

2022-05-27 14:10 UTC, Izothep commented on highcharts-api/highcharts/8-packed-bubble-algorithm/main.js
> +                    if (distanceR < 0.15 && repNode.isParentNode) { //if (force > 4 && repNode.isParentNode) {
Out of curiosity, why you have not used force in here? :)

2022-05-27 14:10 UTC, Izothep commented on highcharts-api/highcharts/8-packed-bubble-algorithm/main.js
> +    H.wrap(H.layouts.packedbubble.prototype, 'repulsiveForces', function (proceed) {
Similar as before, it is not a wrap, but function override.

2022-05-27 14:10 UTC, Izothep commented on highcharts-api/highcharts/8-packed-bubble-algorithm/main.js
> +                        repNode.series.color = randomColor;
Why do we need all of them?

2022-05-27 14:10 UTC, Izothep commented on highcharts-api/highcharts/8-packed-bubble-algorithm/main.js
> +                    if (distanceR < 0.15 && repNode.isParentNode) { //if (force > 4 && repNode.isParentNode) {
btw. Is it possible to check this if statement only for `parentNodes`? (perhaps they have the separate layout algorithm we can check at the beginning?)

2022-06-20 08:32 UTC, hubertkozik commented on highcharts-api/highcharts/8-packed-bubble-algorithm/main.js
> +                    if (distanceR < 0.15 && repNode.isParentNode) { //if (force > 4 && repNode.isParentNode) {
> 

That's because we spoke about how my colleagues had done it and I wanted to show another way to check collision (other than part 2 of this exercise).

2022-07-25 14:54 UTC, Izothep commented on highcharts-api/highcharts/8-packed-bubble-algorithm/main.js
> +                if(repNode.isParentNode){
spaces :)

2022-07-25 14:55 UTC, Izothep approved these changes

2023-12-12 08:49 UTC, closed without merging