exercise/highcharts-9-part1
blacklabel/highcharts-fundamentals-hubertkozik pull request #8
Opened 2022-05-10 08:47 UTC by hubertkozik

2022-05-31 14:35 UTC, Izothep requested changes
In general ok, works well. What about using the projections module? :) 

One important note is to position variables at the beginning of the methods etc. so it is easier to trail their change through the whole function - you can see all the variables from the beginning. And if there is to much of them, then maybe it is time to add an internal method inside of an existing one.

2022-06-20 09:07 UTC, hubertkozik commented on highcharts-api/highcharts/9-3d-charts/main.js
> +        newShadow.push(null);
To create a space between drawn dots, if there won't be 'nulls', points would be joined together with some paths/areas.

2022-06-20 10:48 UTC, hubertkozik commented on highcharts-api/highcharts/9-3d-charts/main.js
> +        color: color,
Yes, it is passed from`chart.events.load` function

2022-06-20 10:53 UTC, hubertkozik commented on highcharts-api/highcharts/9-3d-charts/main.js
> +                    color: 'rgba(0,0,0,1)',
Changed to just 'black'.

2022-06-20 10:57 UTC, hubertkozik commented on highcharts-api/highcharts/9-3d-charts/main.js
> +                            ? -1
Yes, it is working.

2022-06-20 10:59 UTC, hubertkozik commented
According to the projections module - I didn't find it when I was doing that exercise - it could be much more easier with that module :)

2022-07-25 14:53 UTC, Izothep approved these changes

2023-12-12 08:50 UTC, closed without merging